---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy:
    collections:
      - name: awx.awx
        version: 21.7.0
      - name: infra.controller_configuration
        version: 2.11.0

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - dest: configs
    src: ../ansible.cfg

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG AH_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
